### ISSUE TITLE
ensure that data from activity probe is sent to server

### ISSUE THREAD

**Issue by ktkarhu** [aalto-trafficsense/regular-routes-client#12]

**Comment by jannesuo** [comment]
Data is now received in client but is not yet sent to server. Android defines integer values for each activity types. We should decide whether to send the data as integer and then 'translate' it in the server by using enumeration type of table or to send some kind of string representation (word) as activity data.

We should also consider linking one activity (latest) to each location point that is sent to server.

**Comment by jannesuo** [comment]
I'm about to update server + client to support activity data:

New data packet that is sent to server looks like the following (taken from debug server setup receiving end):

[{
	u'activityData': {
		u'activities': [{
			u'confidence': 29,
			u'activityType': u'IN_VEHICLE'
		},
		{
			u'confidence': 45,
			u'activityType': u'UNKNOWN'
		},
		{
			u'confidence': 17,
			u'activityType': u'STILL'
		}]
	},
	u'location': {
		u'latitude': 60.3108443,
		u'time': 1424034011488,
		u'longitude': 25.0010556,
		u'accuracy': 48.0
	},
	u'time': 1424034016421
},
{
	u'activityData': {
		u'activities': [{
			u'confidence': 33,
			u'activityType': u'IN_VEHICLE'
		},
		{
			u'confidence': 52,
			u'activityType': u'UNKNOWN'
		},
		{
			u'confidence': 12,
			u'activityType': u'STILL'
		}]
	},
	u'location': {
		u'latitude': 60.3108443,
		u'time': 1424034011488,
		u'longitude': 25.0010556,
		u'accuracy': 48.0
	},
	u'time': 1424034024898
},
{
	u'activityData': {
		u'activities': [{
			u'confidence': 33,
			u'activityType': u'IN_VEHICLE'
		},
		{
			u'confidence': 52,
			u'activityType': u'UNKNOWN'
		},
		{
			u'confidence': 12,
			u'activityType': u'STILL'
		}]
	},
	u'location': {
		u'latitude': 60.3108443,
		u'time': 1424034011488,
		u'longitude': 25.0010556,
		u'accuracy': 48.0
	},
	u'time': 1424034037156
},
{
	u'activityData': {
		u'activities': [{
			u'confidence': 33,
			u'activityType': u'IN_VEHICLE'
		},
		{
			u'confidence': 52,
			u'activityType': u'UNKNOWN'
		},
		{
			u'confidence': 12,
			u'activityType': u'STILL'
		}]
	},
	u'location': {
		u'latitude': 60.3108443,
		u'time': 1424034011488,
		u'longitude': 25.0010556,
		u'accuracy': 48.0
	},
	u'time': 1424034044247
},
{
	u'activityData': {
		u'activities': [{
			u'confidence': 33,
			u'activityType': u'IN_VEHICLE'
		},
		{
			u'confidence': 52,
			u'activityType': u'UNKNOWN'
		},
		{
			u'confidence': 12,
			u'activityType': u'STILL'
		}]
	},
	u'location': {
		u'latitude': 60.3108443,
		u'time': 1424034011488,
		u'longitude': 25.0010556,
		u'accuracy': 48.0
	},
	u'time': 1424034056036
}]

* Server db schema has two new tables:
- activity_type (id (PK), activity_type) that has same activity types as Google Activity recognition (this is 'enumeration' table)

- activity_data (id (PK), activity_type_id (FK), device_data_id (FK), ordinal, confidence). This table has rows for each activity data and ordinal defines the order/priority of best guesses for data linked to same device_data_id

* maximum of 3 activities is linked to one location point
