### ISSUE TITLE
Client does not install

### ISSUE THREAD

**Issue by jhollmen** [aalto-trafficsense/regular-routes-client#14]
"Sovellusta ei ole asennettu, Olet jo asentanut samannimisen paketin, jonka allekirjoitus on ristiriidassa tämän paketin kanssa."

**Comment by jannesuo** [comment]
You need to unintall the old application for this to work. We decided to create a common app key for the future relases and thus the old app is not possible to use "upgrade" for the old app (previous was from Joonas).

Ps. Fastest way to uninstall app in Android is to open menu and drag the app icon on top of trash button ("poista", "remove").

**Comment by jannesuo** [comment]
Closing this issue as it is probably already solved.
