### ISSUE TITLE
UI should be scrollable

### ISSUE THREAD

**Issue by ktkarhu** [aalto-trafficsense/regular-routes-client#16]
Jaakko has such a small screen in his device that Visualize button is not visible at the bottom. Is there a way to make UI scrollable on small screens?

**Comment by jannesuo** [comment]
yes, let's add that feature to the next version

**Comment by jannesuo** [comment]
I released version 1.1.1 from the client that has scrolling view for the devices with smaller screens (I tested it with AVD 's image with small screen).
