### ISSUE TITLE
Guided installation of Google Play Services 

### ISSUE THREAD

**Issue by ktkarhu** [aalto-trafficsense/regular-routes-client#17]
If our app notices that Google Play Services is missing or out-dated, app should guide user to install/update it as explained here:
http://developer.android.com/google/play-services/setup.html#ensure

**Comment by jannesuo** [comment]
yes,

No it should inform about it with toast message, but it could be modified to provide the solution as well when available.

**Comment by jannesuo** [comment]
I released version 1.1.1 from the client that shows dialog for user to install Google Play Services if it does not exists or if it is not up-to-date. The check is executed every time user returns to the app. I could verify that the dialog appears by using AVD image but AVD won't support installing it with the dialog, BUT it should work in real device.
