### ISSUE TITLE
Modify registering logic to result same device token for same device on each time

### ISSUE THREAD

**Issue by jannesuo** [aalto-trafficsense/regular-routes-client#25]
Now there are many device id's stored and some of them belongs to the same users. When client lost  its' stored token for any reason and re-registers itself to the server, a new device id is created resulting data linked to many device id's that belongs to the same device.

It would be better to have some hash value created from device token that server uses to generate device token so that registering same device twice would result with same token and therefore the same device stays linked to its own data.

**Comment by ktkarhu** [comment]
Use google authentication

**Comment by jannesuo** [comment]
This implementation is now done and committed. It requires both client+server upgrade at the same time and it won't allow data from the old client versions anymore since they are not properly authenticated.

-> Updating server must be well coordinated and users properly notified.

**Comment by jannesuo** [comment]
This issue is completed (with authentication implementation)
