### ISSUE TITLE
Power-saving when device is still

### ISSUE THREAD

**Issue by MJRinne** [aalto-trafficsense/regular-routes-client#29]
When activity recognition reports that the phone is "still", the "still"-condition could be logged only once and location sensing could be relaxed until movement is detected again.

Some hysteresis (e.g. phone still for 30 seconds) is needed to avoid toggling the location provider constantly on and off.

**Comment by ktkarhu** [comment]
I implemented a new ActivityFilterProbe that starts/stop between movement/still and FusedLocationProbe is a StateListener for it and basically follows the state. Whereas Accelerometer and OrientationProbes use ActivityFilterProbe as a schedule and thus collect data for specified duration whenever filter sends any data. I will test this for few days to ensure that everything works as expected.
