### ISSUE TITLE
Add about / credits

### ISSUE THREAD

**Issue by ktkarhu** [aalto-trafficsense/regular-routes-client#35]
We should add about / credits screen:
* This software has been developed in Aalto University as part of Trafficsense project funded by Aalto Energy Efficiency program
* state that this software is published open-source using MIT license at github
* acknowledge that we use Funf that is published under LGPL
* attribute the logos/graphics etc 
* give credit to all our developers (in alphabetical order?)
* show version number of the app

Make it so that this text is read from a text file so that it can be easily edited.

**Comment by jannesuo** [comment]
Done
