### ISSUE TITLE
Google authentication fails with "Error: Unknown" message

### ISSUE THREAD

**Issue by ktkarhu** [aalto-trafficsense/regular-routes-client#38]
I tried to build and run latest version from the master, but for some reason Google authentication fails with a message "Error: Unknown". 

Environment: Nexus 5, Android 5.1

Below is the debug log:

04-24 18:54:35.094    5483-5483/fi.aalto.trafficsense.regularroutes I/LoginActivity﹕ Login: onConnected
04-24 18:54:35.141    5483-6047/fi.aalto.trafficsense.regularroutes I/PlayServiceHelper$RetrieveAuthenticationInfoTask﹕ Google id: 112297930220513078965
04-24 18:54:35.597    5483-6047/fi.aalto.trafficsense.regularroutes E/PlayServiceHelper$RetrieveAuthenticationInfoTask﹕ Retrieving token error: Unknown
04-24 18:54:35.597    5483-5483/fi.aalto.trafficsense.regularroutes E/LoginActivity$4$1﹕ Error in authentication token fetch: Unknown
04-24 18:54:35.598    5483-5483/fi.aalto.trafficsense.regularroutes E/LoginActivity﹕ fetchAndSetAuthenticationTokens: Unknown

**Comment by jannesuo** [comment]
The error visible in debug log is caused when GoogleAuthUtil.getToken() -method throws IOException. Android documentation's sample code states the following cause for IOException in that case:

// network or server error, the call is expected to succeed if you try again later.
 // Don't attempt to call again immediately - the request is likely to
 // fail, you'll hit quotas or back-off.

And the documentation of getToken() -method states:

In the case of a transient (typically network related) error a IOException will be thrown. It is left to clients to implement a backoff/abandonment strategy appropriate to their latency requirements.

**Comment by MJRinne** [comment]
Issue does not manifest at the moment. Either fixed in client code or has been a problem with credentials.
