### ISSUE TITLE
IDEA flags an error for non-gradle Java and gradle-Android modules in the same project

### ISSUE THREAD

**Issue by MJRinne** [aalto-trafficsense/regular-routes-client#40]
Opening the client with Intellij IDEA after a new pull from repo, the following error is printed:

    Unsupported Modules Detected
    Compilation is not supported for following modules: regularroutes. Unfortunately you can't have non-Gradle Java modules and Android-Gradle modules in one project.

**Comment by jannesuo** [comment]
That error occurred to me as well after some Android Studio update. Workaround for it is to modify "settings.gradle" (add empty line or remove one) and then press "sync now" for the appearing message -> The problem disappear.

**Comment by MJRinne** [comment]
Gradle refuses to sync for me, I get the following error message:

    Gradle 'regular-routes-client' project refresh failed
    Error:/Users/rinnem2/Dev/AaltoDSG/TrafficSense/regular-routes-client/external/Funf/AndroidManifest.xml (No such file or directory)

There is no manifest at that location, and I'm pretty sure there shouldn't be. I just didn't figure out yet, why is it being looked for.

**Comment by jannesuo** [comment]
In my working dir there is manifest file under external/Funf

Try execute "update" pull request on all submodules:

git submodule update --init --recursive

**Comment by MJRinne** [comment]
Great, thanks, that fixed it! First time for me to see a git repo, which doesn't fully clone.

I added problem & solution entries for both into the readme.
