### ISSUE TITLE
Energy certificate view details

### ISSUE THREAD

**Issue by SnowblindFatal** [aalto-trafficsense/regular-routes-client#45]
Make a pleasant and informative layout for the energy certificate.

![imag0020](https://cloud.githubusercontent.com/assets/1068367/11163973/0fc0c7dc-8aec-11e5-8a83-1380c5361dfc.jpg)

**Comment by MJRinne** [comment]
Done and merged to master in b0adda2c443c98e90e24e9e7bed78d0d9b108e1b
