### ISSUE TITLE
Notification icon

### ISSUE THREAD

**Issue by ktkarhu** [aalto-trafficsense/regular-routes-client#8]
Jokin notifikaatio ikoni, joka kertoisi, että reitintallennus on
käynnissä, voisi olla kiva pikku lisä. Tämä vahvasti sarjassa "nice to
have", mutta voisi helpottaa asian muistamista, kun ikonin "läsnäoloon"
tottuisi.

Mikko

On 05/12/14 11:34, "Javanainen Joonas" <joonas.javanainen@aalto.fi> wrote:

>Joo, automaattikäynnistystä ei ole toteutettuna nykyisessä versiossa, eli
>boottauksen jälkeen pitää aina käydä käyttöliittymässä.

**Comment by jannesuo** [comment]
Tänään julkaistavassa versiossa on mukana notifikaatio-ikoni.
